server:
  port: ${SERVER_PORT:8081}
  address: 0.0.0.0

# Device Gateway Service - Kafka + Redis Configuration
spring:
  application:
    name: device-gateway-service
  main:
    allow-circular-references: true
  task:
    scheduling:
      pool:
        size: 1
  session:
    idle-timeout: 600  # 10 minutes

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: device-gateway-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        allow.auto.create.topics: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    listener:
      ack-mode: MANUAL_IMMEDIATE

  # Redis Configuration (primary storage)
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 10s
      connect-timeout: 10s
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 10s
        shutdown-timeout: 200ms
      jedis:
        pool:
          enabled: false

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 30m
      cache-null-values: false
      key-prefix: "wheelseye:cache:"
      use-key-prefix: true



device-gateway:
  tcp:
    port: ${TCP_PORT:5023}
    boss-threads: ${TCP_BOSS_THREADS:1}
    worker-threads: ${TCP_WORKER_THREADS:0}
    business-threads: ${TCP_BUSINESS_THREADS:4}
    idle-timeout: ${TCP_IDLE_TIMEOUT:300}
    protocol: ${DEFAULT_PROTOCOL:GT06}

  kafka:
    topics:
      device-sessions: device.sessions
      device-location: location.device
      telemetry-inbound: telemetry.inbound
      commands-outbound: commands.outbound

  session:
    cleanup-interval: ${DEVICE_GATEWAY_SESSION_CLEANUP_INTERVAL:300000}  # FIXED: 5 minutes instead of 60s
    idle-timeout-seconds: ${SESSION_IDLE_TIMEOUT_SECONDS:1800}
    max-sessions: ${MAX_SESSIONS:10000}


# Logging Configuration
logging:
  level:
    root: INFO
    com.wheelseye.devicegateway: DEBUG
    org.springframework.data.redis: INFO
    org.springframework.cache: INFO
    io.netty: INFO
    org.apache.kafka: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n"
  file:
    name: logs/device-gateway.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
      total-size-cap: 1GB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches,sessions,redis
  endpoint:
    health:
      show-details: always
    redis:
      enabled: true