server:
  port: ${SERVER_PORT:8081}
  address: 0.0.0.0

# Device Gateway Service - Kafka + Redis Configuration
spring:
  application:
    name: device-gateway-service
  main:
    allow-circular-references: true
  task:
    scheduling:
      pool:
        size: 1

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: device-gateway-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        allow.auto.create.topics: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    listener:
      ack-mode: MANUAL_IMMEDIATE

  # Redis Configuration (primary storage)
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 300000  # 5 minutes
      cache-null-values: false
    cache-names:
      - device-sessions
      - session-stats
      - session-by-imei



device-gateway:
  tcp:
    port: ${TCP_PORT:5023}
    boss-threads: ${TCP_BOSS_THREADS:1}
    worker-threads: ${TCP_WORKER_THREADS:0}
    business-threads: ${TCP_BUSINESS_THREADS:4}
    idle-timeout: ${TCP_IDLE_TIMEOUT:300}
    protocol: ${DEFAULT_PROTOCOL:GT06}

  kafka:
    topics:
      device-sessions: device.sessions
      device-location: location.device
      telemetry-inbound: telemetry.inbound
      commands-outbound: commands.outbound

  session:
    cleanup-interval: ${DEVICE_GATEWAY_SESSION_CLEANUP_INTERVAL:300000}  # FIXED: 5 minutes instead of 60s
    idle-timeout-seconds: ${SESSION_IDLE_TIMEOUT_SECONDS:1800}
    max-sessions: ${MAX_SESSIONS:10000}


# Logging Configuration
logging:
  level:
    com.wheelseye.devicegateway: INFO
    com.wheelseye.devicegateway.protocol: DEBUG
    com.wheelseye.devicegateway.service: DEBUG
    com.wheelseye.devicegateway.repository: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    root: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/device-gateway.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches,sessions,redis
  endpoint:
    health:
      show-details: always
    redis:
      enabled: true
